baseURL: "https://inwardmovement.github.io/"
title: "Inward Movement"
canonifyURLs: false
relativeURLs: false
disableFastRender: true
disableLiveReload: true
metaDataFormat: yaml
rssLimit: 10
enableRobotsTXT: true
enableEmoji: true
disableKinds:
- taxonomy
- term
params:
  description: "Poèmes"
  author: "Victor"
author:
  name: "Victor"
security:
  funcs:
    getenv: ['^HUGO_', 'PRODUCTION', 'GITHUB_SHA']
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: false
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: blackfriday
    renderer:
      hardWraps: true
      unsafe: true
      xHTML: false
  tableOfContents:
    startLevel: 1
    endLevel: 5
