[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview.environment]
  SITE="${DYNAMIC_DEPLOY_PRIME_URL}"

[context.branch-deploy.environment]
  SITE="${DYNAMIC_DEPLOY_PRIME_URL}"
