[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview.environment]
  command = "SITE=${DEPLOY_PRIME_URL} astro build"

[context.branch-deploy.environment]
  command = "SITE=${DEPLOY_PRIME_URL} astro build"
