[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview.environment]
  command = "SITE=${DYNAMIC_DEPLOY_PRIME_URL} npm run build"

[context.branch-deploy.environment]
  command = "SITE=${DYNAMIC_DEPLOY_PRIME_URL} npm run build"
