name: deploy-main

on:
  push:
    branches:
      - main

env:
  NETLIFY_SITE_ID: 'bcfd8fc4-c727-4bad-b39c-d1a4e5c46cd1'
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_VAJM }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Deploy site
      run: npx netlify-cli deploy --prod --dir .
      if: success()
