name: deploy-main

on:
  push:
    branches:
      - main

env:
  PRODUCTION: true
  HUGO_VERSION: '0.92.0'
  NODE_VERSION: '16.13.2'
  NETLIFY_SITE_ID: 'bcfd8fc4-c727-4bad-b39c-d1a4e5c46cd1'
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_VAJM }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
      if: success()
    - name: Install dependencies
      run: |
        npm ci --no-optional
        npm i -g postcss postcss-cli autoprefixer gulp-cli
      if: success()
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: ${{ env.HUGO_VERSION }}
        extended: true
      if: success()
    - name: Build site
      run: npm run _build
      if: success()
    - name: Deploy site
      run: npx netlify-cli deploy --prod --dir public
      if: success()
